### ISSUE TITLE
Expo SDK 49 Node v16

### ISSUE THREAD

**Issue by githubjeka** [EvanBacon/expo-apple-targets#27]
I add `"@bacons/apple-targets": "*",` in package.json

Run `eas build --platform ios --profile release` and get an error for task `Run fastlane`

After research Xcode Logs get error: 

```
IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-rncore.build/Script-46EB2E00022E30.sh
Node found at: /Users/expo/.nvm/versions/node/v16.18.1/bin/node
/Users/expo/workingdir/build/node_modules/cliui/build/index.cjs:291
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/expo/workingdir/build/node_modules/string-width/index.js from /Users/expo/workingdir/build/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /Users/expo/workingdir/build/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/cliui/build/index.cjs:291:21)
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/yargs/build/index.cjs:1:60678)
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/react-native/scripts/generate-specs-cli.js:12:15) {
  code: 'ERR_REQUIRE_ESM'
}
Command PhaseScriptExecution failed with a nonzero exit code
```

Any thoughts on how to fix this ?

**Comment by wodin** [comment]
Try upgrading to Node 18 or 20.
Also try removing your lock file and `node_modules` and reinstalling your dependencies. Then run `npx expo install --fix`

**Comment by githubjeka** [comment]
Answers from the Internet were checked first. Does not help.

**Comment by wodin** [comment]
See these:
* [expo#26459](https://github.com/expo/expo/pull/26459/files#diff-4029deeca10da27c3fc749ee3cd9f8244e99169a56169e9f060c3afaf5a2d6a6L46)
* [jackspeak#5](https://github.com/isaacs/jackspeak/issues/5)

Maybe add resolutions/overrides for this:
"sucrase": "3.34.0"

**Comment by githubjeka** [comment]
Thanks. Fixed.

Added to `package.json`

```
  "resolutions": {
    "jackspeak": "2.1.1"
  },
```
