### ISSUE TITLE
prebuild with blank template conflicts with @sentry/react-native 

### ISSUE THREAD

**Issue by jmatsushita** [EvanBacon/expo-apple-targets#66]
Hi there,

Thanks for the great project! I wanted to report that using the `prebuild-blank.tgz` template for prebuild while having `@sentry/react-native` installed fails with the following error:

```
> bun prebuild -p ios --template ../../node_modules/@bacons/apple-targets/prebuild-blank.tgz
$ expo prebuild -p ios --template ../../node_modules/@bacons/apple-targets/prebuild-blank.tgz
✔ Created native directory
› Using current versions instead of recommended react-native@0.76.3.
✔ Updated package.json | no changes
⠦ Running prebuild
Using experimental Config Plugin @bacons/apple-targets that is subject to breaking changes.
✖ Prebuild failed
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'shellScript')
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'shellScript')
    at modifyExistingXcodeBuildScript (/Users/jun/dev/iios/node_modules/@sentry/react-native/plugin/build/withSentryIOS.js:56:17)
    at /Users/jun/dev/iios/node_modules/@sentry/react-native/plugin/build/withSentryIOS.js:43:9
    at action (/Users/jun/dev/iios/node_modules/expo/node_modules/@expo/config-plugins/build/plugins/withMod.js:199:29)
    at interceptingMod (/Users/jun/dev/iios/node_modules/expo/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:27)
    at action (/Users/jun/dev/iios/node_modules/@expo/cli/node_modules/@expo/config-plugins/build/plugins/withMod.js:204:14)
    at async interceptingMod (/Users/jun/dev/iios/node_modules/@expo/cli/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/jun/dev/iios/node_modules/@expo/cli/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/jun/dev/iios/node_modules/@expo/cli/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/jun/dev/iios/node_modules/@expo/cli/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/jun/dev/iios/node_modules/@expo/cli/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
```

It [seems that](https://github.com/getsentry/sentry-react-native/blob/main/packages/core/plugin/src/withSentryIOS.ts#L48-L55) `@sentry/react-native` expects the `script.shellScript` to be populated, and it fails currently because it's undefined, and even if there was a guard, it would warn and bail.

Cheers,

Jun

**Comment by EvanBacon** [comment]
The entire point of the blank template is to not have React Native, it's not going to work if you have config plugins that expect React Native. Use something like app.config.js to dynamically remove plugins based on environment variables to conditionally disable all plugins if you want to test with the blank prebuild template.
