### ISSUE TITLE
Cannot add mod to "ios.xcodeProjectBeta2" because the provider has already been added. Provider must be the last mod added

### ISSUE THREAD

**Issue by patrickkeenan** [EvanBacon/expo-apple-targets#75]
Getting this error when trying to prebuild:

`npx expo prebuild -p ios --clean`

Here's the error

```
PluginError: Cannot add mod to "ios.xcodeProjectBeta2" because the provider has already been added. Provider must be the last mod added.
PluginError: Cannot add mod to "ios.xcodeProjectBeta2" because the provider has already been added. Provider must be the last mod added.
    at withBaseMod (/Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:93:13)
    at withMod (/Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:187:10)
    at withXcodeProjectBeta (/Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@bacons/apple-targets/build/withXcparse.js:33:41)
    at withXcodeChanges (/Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@bacons/apple-targets/build/withXcodeChanges.js:16:51)
    at withWidget (/Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@bacons/apple-targets/build/withWidget.js:181:45)
    at /Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@bacons/apple-targets/build/config-plugin.js:41:43
    at Array.forEach (<anonymous>)
    at withTargetsDir (/Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@bacons/apple-targets/build/config-plugin.js:28:13)
    at withStaticPlugin (/Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:146:12)
    at /Users/patrickkeenan/Documents/GitHub/talkie-app/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:84
```

**Comment by patrickkeenan** [comment]
Seems like it might be a conflict with static imports. But I need those to use react-native-firebase
https://rnfirebase.io/

```
"ios": {
    "useFrameworks": "static"
}
```

**Comment by EvanBacon** [comment]
Maybe you're adding the config plugin twice. Shouldn't overlap with useFrameworks.

**Comment by EvanBacon** [comment]
Closing as there's no repro and nothing I can do to help resolve the issue.

**Comment by azizsaad** [comment]
I got this same error when attempting to use this package with `react-native-device-activity`

I think the issue is that both plugins attempted to use a provider to make the last changes to the native ios code.

I fixed it by removing the `activity` plugin and adding the native plugin changes for the `activity` plugin in `expo.extra.eas.build.experimental.ios`
